# Change these first
owner: tannerln7 # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: Plex
    url: $PLEX
  - name: Overseer
    url: $OVERSEERR
  - name: Episodes API
    url: $SONARR
  - name: Movie API
    url: $RADARR
  - name: Download Client
    url: $NZBGET
  - name: Download Server
    url:  $DOWNLOAD_SERVER
    slug: download-server

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tannerln7.com
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Server Uptime**"
  introMessage: "**Real-time** status updates"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
