name: NNTP Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: python3 -m pip install pyyaml pynntp

      - name: Run NNTP check
        env:
          UN_SERVER:    ${{ secrets.UN_SERVER }}
          UN_PORT:      ${{ secrets.UN_PORT }}
          UN_USERNAME:  ${{ secrets.UN_USERNAME }}
          UN_PASSWORD:  ${{ secrets.UN_PASSWORD }}
        run: python3 .github/workflows/scripts/un-check.py

      - name: Commit history file
        run: |
          git config user.name  "Upptime Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add history/unet.yml
          git commit -m ":memo: unet status update [skip ci]" || echo "No changes"
          git push